event_inherited();
image_xscale = 4;
image_yscale = 4;
damage = 13;
doesShoot = true;
shotType = objNucleurBullet;
HP = 20;
moveSpeed = 1;
moveSpeedMax = 2;
moveSpeedMin = 1;
doesPoison = true;
poisonDamage = 6;
poisonTime = 5*60;