event_inherited()
grav = 2;
burnOnThinkChance = 100;
//burnTime  = 1000;
//burnTimeMax = 
moveSpeedMax = 4;
moveSpeedMin = 1;
jumpChanceOnThink = 0;
moveType = AI.agressive;
damage = 1;
vanish = true;
vanishcdmax = 60*5;
vanishcd = vanishcdmax;
burnOnHit = 60;
hurtsToTouch = true;
damage = 1;
yPush = -1;
xPush = 1;
fat = 6.5;
